### ISSUE TITLE
org.pentaho.di.core 依赖问题

### ISSUE THREAD

**Issue by 1005568045** [xuanbo/kettle-web#1]
org.pentaho.di.core 这个包时哪个依赖   没动代码个依赖，运行就报这个包里很多没有。

**Comment by 1005568045** [comment]
我发现是 pentaho的jar下载都失败了

**Comment by xuanbo** [comment]
> 我发现是 pentaho的jar下载都失败了

kettle的jar都在私服里：https://nexus.pentaho.org/content/groups/omni/

**Comment by xuanbo** [comment]
> 我发现是 pentaho的jar下载都失败了

kettle的jar都在私服里：https://nexus.pentaho.org/content/groups/omni/。而且包太挺多的，可能需要FQ

**Comment by 1005568045** [comment]
fq是啥意思  没弄过私服   
<repository>
            <id>pentaho</id>
            <name>pentaho maven</name>
            <url>https://nexus.pentaho.org/content/groups/omni/</url>
       </repository>  这里还有有地址  下载不了

**Comment by 1005568045** [comment]
> fq是啥意思 没弄过私服
> 
> pentaho
> pentaho maven
> https://nexus.pentaho.org/content/groups/omni/
> 这里还有有地址 下载不了

**Comment by 1005568045** [comment]
是要一个个下载下来  maven安装在本地吗

**Comment by xuanbo** [comment]
> 是要一个个下载下来 maven安装在本地吗

就是说kettle的jar在国外，然后国内下载很慢，容易超时，你需要挂代理下载包。直接mvn clean package -DskipTests就好了，然后本地IDE运行就好了
