### ISSUE TITLE
log日志错误

### ISSUE THREAD

**Issue by shinemeteor** [xuanbo/kettle-web#14]
两个问题 1、某些日志输出乱码
                2、Failure obtaining db row lock "对象名无效" 错误

如图：
![QQ图片20200914101632](https://user-images.githubusercontent.com/13598284/93036773-61297400-f673-11ea-89fb-4ceadc1c25a3.png)

我的数据源（database-platform: org.hibernate.dialect.SQLServer2008Dialect）是用SQLServer

**Comment by xuanbo** [comment]
1. 日志乱码是因为加了色彩输出，如果你在linux下的终端下看，就会有颜色（比如ERROR是红色）
2. 对象名无效是否因为数据库未支持大小写，需要设置

**Comment by shinemeteor** [comment]
> 1. 日志乱码是因为加了色彩输出，如果你在linux下的终端下看，就会有颜色（比如ERROR是红色）
> 2. 对象名无效是否因为数据库未支持大小写，需要设置

我用的sqlserver 请问 怎么设置呢

**Comment by xuanbo** [comment]
![image](https://user-images.githubusercontent.com/15867447/93183163-3cb1c280-f76d-11ea-9d4f-49e622e032e7.png)
用sqlserver的quartz建表语句
