### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by mochengdong** [xuanbo/kettle-web#19]
![image](https://user-images.githubusercontent.com/40670644/128836174-927d4c07-c9f7-403b-a485-9ac007f571bb.png)

java: 读取XXX\repository\org\mozilla\javascript\1.7.2\javascript-1.7.2.jar时出错; error in opening zip file
java: java.lang.RuntimeException: java.io.IOException: Error reading file C:\software\repository\org\mozilla\javascript\1.7.2\javascript-1.7.2.jar: error in opening zip file
本地仓库有该jar包

**Comment by niefansheng** [comment]
你好。你解决掉这个问题了吗？

**Comment by xuanbo** [comment]
@mochengdong @niefansheng 目前如下包依赖存在问题，会导致编译错误：

[WARNING] The POM for pentaho-kettle:kettle-core:jar:7.1.0.0-12 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for pentaho-kettle:kettle-engine:jar:7.1.0.0-12 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for pentaho-kettle:kettle-dbdialog:jar:7.1.0.0-12 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.mozilla:javascript:jar:1.7.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.oracle:ojdbc7:jar:12.1.0.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

解决方案：

1. 删除本地maven仓库中的pentaho-kettle、org.mozilla. javascript依赖
2. 更新仓库
3. 执行maven编译：mvn clean compile -DskipTests

目前存在问题：

database type with plugin id [HIVE2] couldn't be found!
