### ISSUE TITLE
项目无法运行

### ISSUE THREAD

**Issue by oxcz** [xuanbo/kettle-web#24]
打包能正常打包，直接run和打包后运行都是在启动banner就停了，是因为什么呢？
没有任何日志
<img width="416" alt="image" src="https://user-images.githubusercontent.com/16790410/155466073-f16a9ce8-500a-4003-8748-efff3ec3532a.png">

**Comment by oxcz** [comment]
直接运行项目会卡在这个输出
ibernate: select jobdto0_.id as id1_0_0_, jobdto0_.create_at as create_a2_0_0_, jobdto0_.update_at as update_a3_0_0_, jobdto0_.description as descript4_0_0_, jobdto0_.group_id as group_id5_0_0_, jobdto0_.name as name6_0_0_, jobdto0_.path as path7_0_0_ from job jobdto0_ where jobdto0_.id=?
Hibernate: select jobdto0_.id as id1_0_0_, jobdto0_.create_at as create_a2_0_0_, jobdto0_.update_at as update_a3_0_0_, jobdto0_.description as descript4_0_0_, jobdto0_.group_id as group_id5_0_0_, jobdto0_.name as name6_0_0_, jobdto0_.path as path7_0_0_ from job jobdto0_ where jobdto0_.id=?
Hibernate: select jobdto0_.id as id1_0_0_, jobdto0_.create_at as create_a2_0_0_, jobdto0_.update_at as update_a3_0_0_, jobdto0_.description as descript4_0_0_, jobdto0_.group_id as group_id5_0_0_, jobdto0_.name as name6_0_0_, jobdto0_.path as path7_0_0_ from job jobdto0_ where jobdto0_.id=?
Hibernate: select jobdto0_.id as id1_0_0_, jobdto0_.create_at as create_a2_0_0_, jobdto0_.update_at as update_a3_0_0_, jobdto0_.description as descript4_0_0_, jobdto0_.group_id as group_id5_0_0_, jobdto0_.name as name6_0_0_, jobdto0_.path as path7_0_0_ from job jobdto0_ where jobdto0_.id=?
Hibernate: select jobdto0_.id as id1_0_0_, jobdto0_.create_at as create_a2_0_0_, jobdto0_.update_at as update_a3_0_0_, jobdto0_.description as descript4_0_0_, jobdto0_.group_id as group_id5_0_0_, jobdto0_.name as name6_0_0_, jobdto0_.path as path7_0_0_ from job jobdto0_ where jobdto0_.id=?
Hibernate: select jobdto0_.id as id1_0_0_, jobdto0_.create_at as create_a2_0_0_, jobdto0_.update_at as update_a3_0_0_, jobdto0_.description as descript4_0_0_, jobdto0_.group_id as group_id5_0_0_, jobdto0_.name as name6_0_0_, jobdto0_.path as path7_0_0_ from job jobdto0_ where jobdto0_.id=?

**Comment by xuanbo** [comment]
日志输出到logs目录了
