### ISSUE TITLE
你好，请问任务怎么停止呢？我有一个任务一直是正在运行，其他任务再开始的时候都是等待运行，一次只能运行一个任务吗？

### ISSUE THREAD

**Issue by dsykoo** [xuanbo/kettle-web#25]

**Comment by xuanbo** [comment]
1. 任务提交到线程池，进行并发。应该是表job_history的log_text字段长度不够，调整为longblob
2. 任务停止，之前基于quartz实现的（QuartzJobService）。没有做暂停、恢复功能。

**Comment by xuanbo** [comment]
应该是表job_history的log_text字段长度不够，导致存储日志时错误，造成任务状态一直为等待运行

**Comment by dsykoo** [comment]
定时作业创建报错，说没有qrtz_locks表，是怎么回事呀？

**Comment by dsykoo** [comment]
定时任务创建时报错，说没有qrtz_locks表，是怎么回事呀
![IMG_20220414_172001](https://user-images.githubusercontent.com/102141580/163394019-73594a27-1e73-44f4-b938-beb8bb1075ef.jpg)
？

**Comment by xuanbo** [comment]
要创建quartz相关的表，quartz包中的org/quartz/impl/jdbcjobstore/tables_mysql_innodb.sql

**Comment by dsykoo** [comment]
建好了，能创建定时任务了，但是它启动不了，能加个联系方式吗
![image](https://user-images.githubusercontent.com/102141580/163510452-8903e2ea-f2ef-4710-95e0-d8989179f77b.png)

**Comment by xuanbo** [comment]
是否有错误

**Comment by dsykoo** [comment]
控制台没有报错，也没有显示运行job
![$6)X2(NC4BM0())9~YB(YC3](https://user-images.githubusercontent.com/102141580/163513385-0caac5ed-1ec3-4ec3-a88d-39fe6ff7e309.png)

**Comment by dsykoo** [comment]
谢谢可以了，我pom文件有问题

**Comment by dsykoo** [comment]
任务变量怎么用呢？还有任务组是不是可以去掉，任务组有什么作用呢

**Comment by xuanbo** [comment]
任务变量是传递到kjb中，让里面使用。任务组没啥用，单纯分个组，管理下
