### ISSUE TITLE
您好，支持调度资源库里面的流程么，流程里面包含大数据插件的步骤能执行么

### ISSUE THREAD

**Issue by jake-wx** [xuanbo/kettle-web#8]
不好意思哈，项目的jar包有点难下，没看到如何评论，只能发个issue提问哈~~

**Comment by xuanbo** [comment]
> 不好意思哈，项目的jar包有点难下，没看到如何评论，只能发个issue提问哈~~

应该不支持调度资源库里面的，只是运行本地的kjb、ktr。流程目前只覆盖了hive sql，其他大数据插件未测试，不过只需要引入相关的插件依赖。
